### ISSUE TITLE
Must have dataset tests for templates?

### ISSUE THREAD

**Issue by chrzyki** [lexibank/template#3]
Most of our datasets lack basic tests (e.g. tests against expected number of lexemes, languages, concepts, etc.). Do you think it would be useful to have another file in here (a la https://github.com/lexibank/transnewguineaorg/blob/master/test.py) with a template for basic tests?

**Comment by xrotwang** [comment]
I'd consider this repos just a proposal for a dataset template, right? The actual implementation of the template should go here https://github.com/lexibank/pylexibank/tree/v2/src/pylexibank/dataset_template
So for tests, that would mean adding a file `test.py`, overwriting the `cldfbench` default https://github.com/cldf/cldfbench/blob/master/src/cldfbench/dataset_template/test.py

**Comment by chrzyki** [comment]
Yup, just thought this was the place to discuss this.

**Comment by LinguList** [comment]
For me, this repo is something like a place where I pick a template, manually, and then start working. And I was thinking of a bigger collection of templates for different purposes, thus, a complex one, as the one I originally proposed, a short one, etc. So if that complexity could also go into pylexibank, by offering like 5-10 templates depending on purpose (or by having a system of plugs by which the template is constructed), this would be nice, otherwise, we have to discuss (and this is anyway not done yet), how to organize this repo here.

**Comment by xrotwang** [comment]
I think this should go into pylexibank. Templates are just [registered by entry point](https://github.com/lexibank/pylexibank/blob/cbba6c089f730d2118dc36bda829486318cbe0a5/setup.py#L23-L25) and can then be used with `cldfbench new`. The problem with a static collection here is that - e.g. - the dataset ID is used in different places - filenames, the python module, etc. - and this usage should be synchronized.

**Comment by xrotwang** [comment]
5-10 templates would mean 5-10 short classes here https://github.com/lexibank/pylexibank/blob/cbba6c089f730d2118dc36bda829486318cbe0a5/src/pylexibank/scaffold.py#L9-L14
The nice thing is, that they can also inherit templates from others, by listing the template directory of the base template first.

**Comment by LinguList** [comment]
okay, with `cldfbench new`, can I then pick different templates? Or should we break into blocks? E.g., do I write:

```
cldfbench new --dataset-id=template --language-class=custom concept-class=custom --cognate-class=custom --entry-class=custom --concept-list=Swadesh-1952-200 --imports=clldutils,lingpy
```
or something similar?

**Comment by LinguList** [comment]
Ah, excellent, this is straightforward. I may need a short example on how to get started, but could then expend on certain points (e.g., we need `add_value`, `add_form`, etc. to be clearly exposed).

**Comment by xrotwang** [comment]
```
$ cldfbench new -h
usage: cldfbench new [-h] [--template {cldfbench,lexibank}] [--out OUT]

Create a skeleton for a new dataset

optional arguments:
  -h, --help            show this help message and exit
  --template {cldfbench,lexibank}
                        Template type (default: cldfbench)
  --out OUT             Directory in which to create the skeleton (default: .)
```

**Comment by LinguList** [comment]
Okay, so we'd just have to add options or template types then. E.g. passing name and ID before would already save some time...

**Comment by xrotwang** [comment]
Name and ID will be collected when running `cldfbench new`. A `Template` has an attribute `metadata`, which points to a subclass of `cldfbench.Metadata` (see https://github.com/cldf/cldfbench/blob/55f420dcc9b58ec7d9bf22ac84395d8955496fdd/src/cldfbench/metadata.py#L13-L107).

The attributes of this metadata class - when marked with `elicit=True` - will be collected when running `cldfbench new` and then be available as template variables when rendering the files (and file names) of the skeleton.

**Comment by SimonGreenhill** [comment]
A strong yes from me on testing all the tables (languages, concepts, forms, cognates), preferably both nrows and a value. I did [this](https://github.com/lexibank/dravlex/blob/master/test.py) for dravlex , and [this](https://github.com/lexibank/birchallchapacuran/blob/master/test.py) for birchallchapacuran and it makes me sleep better at night :)

**Comment by LinguList** [comment]
I think we'll need one example for a basic template if / when this is ready, as I cannot really understand how to propose a new one now, but if there's a rough skeleton and explanation on how the arguments work, I'll gladly develop more. For now, I'll do it manually, using the extended py-files. But we should start thinking of increasing complexity if needed, as this was also the reason why we have so many hand-coded parts (with splitting forms and the like) in lexibank now, since nobody followed the proper protocol in the end.

**Comment by SimonGreenhill** [comment]
The problem with allowing python code (or any turing-complete language) is that people can do *anything* :) but this is why I think we should insist on tests: if we know that dataset A generates a valid CLDF dataset containing V languages, W concepts, X forms, Y sources and Z cognates, and that a particularly complicated form is parsed to xxx, then we can refactor easily.

**Comment by LinguList** [comment]
Yes, @SimonGreenhill, but the problem of tests is also that they are betraying if one does not look into the data generated. E.g., I spotted, when working on the lexibank datasets, that at times we would generate virtual forms, since the code would first split, and then again split automatically, so forms would be duplicated, etc. This reflects what is always the danger when people are too proficient with computers (not blaming anybody here, it includes myself): they trust the code more than their eyes and often do not even look at the data generated.
So one of the things EVERYBODY who creates a cldf dataset should also do is to look at the cldf/forms.csv etc., but it is obvious that this did not always happen. 

And as a second point, we need to be on the same page of the code (which is much easier now, with the new version, I guess).

I think I have looked at far too may lexibank datasets in the last months, but this has also shown me many things one needs to be careful with, and the starting point is having a good template to start with.

**Comment by xrotwang** [comment]
Just a practical note: Should we maybe
- release `cldfbench` and `pylexibank` v2.0,
- refactor the existing datasets accordingly,
- extract what would be useful templates from the re-factoring of existing datasets?

Spending time on templates without doing the above would only seem justified if we had lots of new datasets about to be started right now.

**Comment by chrzyki** [comment]
Releasing sounds good. Infrastructure-wise: Apart from the obvious code-related adaptions needed, do we need to take stock of what needs to be changed in other files?

- `setup.py`: `pylexibank>=2.0` (explicit `cldfbench` needed?)
- `.gitattributes`: are gone?
- anything else?

**Comment by LinguList** [comment]
That was in some sense my idea, without releasing, but that each of us tests:

1. one old dataset in v2
2. and creates a new dataset

and that we use our knowledge there to see what templates are needed.

Somehow, I didn't get any response, so nobody really answered "yes, I'll refactor dataset XYZ", or "yes, I'll look into the suggestion issue #X", but maybe, we had just too many notes, and nobody noticed these ones.

**Comment by chrzyki** [comment]
I'm working on `kitchensemitic` right now.

**Comment by LinguList** [comment]
Please see [here](https://github.com/lexibank/pylexibank/pull/129#issuecomment-544238768) for my suggestions on easy-to-do **new** datasets.

**Comment by SimonGreenhill** [comment]
sorry, I will try get onto it soon (back from holiday and inbox is FULL). Other easy datasets are https://github.com/lexibank/lexibank/issues/171 (needed for numeralbank) and https://github.com/lexibank/lexibank/issues/64 (fills in a blank spot -- Tasmania -- on our map)

**Comment by SimonGreenhill** [comment]
@LinguList re tests: having to implement a test or two means that the implementor has to look at each file in the CLDF output at least once :)

**Comment by LinguList** [comment]
I was prepareing the tasmanian dataset with a student of Gerhard Jäger, but it seems there's not much data, in weird encoding. Yet: if somebody takes on this, I'll forward all we did by then.

**Comment by SimonGreenhill** [comment]
yeah, it's salvage data from long-extinct languages so it's never going to get any better unfortunately :/

**Comment by LinguList** [comment]
Just forgot, in fact, I added the concept list [already](https://concepticon.clld.org/contributions/Bowern-2012-644).
